version: '3'

services:
  browser-stream:
    build: .
    image: alexjonas/webrtc-streamer:latest
    volumes:
      - ./:/home/user/app
    environment:
      - MEETING_URL=https://www.youtube.com/watch?v=p6GhDMnKu3o
      - RTMP_URL=rtmp://..............
    ports:
      - 5900:5900