version: '3'

services:
  browser-stream:
    build: .
    image: alexjonas/webrtc-streamer:latest
    volumes:
      - ./recordings:/home/user/app/recordings
    # environment:
    #   - MEETING_URL=https://www.youtube.com/watch?v=p6GhDMnKu3o
    #   - RTMP_URL=rtmp://..............
    env_file:
      - ./.env
    extra_hosts:
      - "inevent.localhost:192.168.0.108"
    ports:
      - 5900:5900